### ISSUE TITLE
Sniffle2.3 installation issue

### ISSUE THREAD

**Issue by vyx-lucy-kaplun** [fritzsedlazeck/Sniffles#473]
First of all, thank you for that great tool! I have been working with v2.2 and it performs fine most of the time.

Currently I am attempting to run Sniffle2.3 and getting the following issue:
```
2024-04-12 19:58:06,653 INFO sniffles.main (25417): ==============================
2024-04-12 19:58:06,653 WARNING sniffles.dependencies (25417): Dependency psutil not available - resource monitoring is disabled.
...
2024-04-12 19:58:23,356 INFO sniffles.worker (25417): Starting worker 0
2024-04-12 19:58:23,360 ERROR sniffles.worker (25417): Unhandled error in worker 0. This may result in an orphened worker process.
Traceback (most recent call last):
  File "/home/pplnuser/anaconda2/envs/Sniffles2.3_env/lib/python3.10/site-packages/sniffles/parallel.py", line 517, in run_parent
    self.maybe_recycle()
  File "/home/pplnuser/anaconda2/envs/Sniffles2.3_env/lib/python3.10/site-packages/sniffles/parallel.py", line 494, in maybe_recycle
    recycle = self.recycle(self.id, self.process.pid) if callable(self.recycle) else self.recycle
  File "/home/pplnuser/anaconda2/envs/Sniffles2.3_env/lib/python3.10/site-packages/sniffles/utils/resmon.py", line 137, in __call__
    if worker_pid in self._workers:
AttributeError: 'ResourceMonitor' object has no attribute '_workers'
```

At the same time it looks like all requirements are satisfied:
```
pip show psutil 
Name: psutil
Version: 5.9.8

pip show pysam
Name: pysam
Version: 0.22.0

python3 --version
Python 3.10.14
```

Sniffles2.2 runs just fine, so I assume the issue is specifically with v2.3

**Comment by hermannromanek** [comment]
Hi @vyx-lucy-kaplun,

Thanks for reporting this - yes this is indeed an issue with 2.3, probably due to it not being able to import psutil - I'll investigate.

From the looks of it you are running inside a conda environment, is psutil installed in that environment (this would usually not happen via pip but conda)? Can you please try the following steps?

`conda list -n Sniffles2.3_env`

In case it is not there, you should be able to install it using 

`conda install psutil -n Sniffles2.3_env`

Thanks,

Hermann

**Comment by vyx-lucy-kaplun** [comment]
@hermannromanek 
Thank you! 
Here is the output of `conda list:`
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
edlib                     1.3.9                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
numpy                     1.26.4                   pypi_0    pypi
openssl                   3.2.1                hd590300_1    conda-forge
pandas                    2.2.2                    pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
psutil                    5.9.8                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sniffles                  2.3.2              pyhdfd78af_0    bioconda
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024.1                   pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by vyx-lucy-kaplun** [comment]
I have tried `conda install psutil `in the environment, and it did resolve the issue. Thank you!

**Comment by lfpaulin** [comment]
Hi @vyx-lucy-kaplun 
we have updated the conda recipe such that this error does not happen again
psutil should have been automatically installed alongside sniffles
I tested the new build in conda and it works, please let us know if you find another issue
